# Generated by Django 6.0.2 on 2026-03-12 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acc_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Acc_details',
            fields=[
                ('acc_number', models.BigAutoField(default=1234567890, primary_key=True, serialize=False)),
                ('balance', models.BigIntegerField(default=1000)),
                ('pin', models.CharField(default=0)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('adhar', models.PositiveIntegerField(unique='True')),
                ('email', models.EmailField(max_length=254, unique='True')),
                ('address', models.TextField()),
                ('nomini_name', models.CharField(max_length=30)),
                ('acc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acc_type')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gender')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.relation')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
    ]
