# Generated by Django 6.0.2 on 2026-03-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acc_details',
            old_name='State',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='acc_details',
            name='acc_number',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
