# Generated by Django 6.0.2 on 2026-03-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_state_acc_details_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_details',
            name='pin',
            field=models.CharField(default='0000'),
        ),
    ]
